name: "Delete Source Map Action"
description: "Delete source map of JavaScript and CSS."
author: "Ubie, Inc."
inputs:
  directory:
    required: true
    description: "The directory that contains the build result such as JavaScript, CSS, and source map."

runs:
  using: "composite"
  steps:
    - run: |
        find ${{ inputs.directory}} -name "*.map" -delete
        find ${{ inputs.directory}} -name "*.js" | xargs sed -i -e '/\/\/# sourceMappingURL.*/d'
        find ${{ inputs.directory}} "*.css" | xargs sed -i -e '/\/\*# sourceMappingURL.*/d'
      shell: bash
