name: "Delete Source Map Action"
description: "Delete source map from web frontend distribution."
author: "Ubie, Inc."
branding:
  icon: "delete"
  color: "yellow"

inputs:
  directory:
    required: true
    description: "The directory that contains the build result such as JavaScript, CSS, and source map."

runs:
  using: "composite"
  steps:
    - run: |
        find ${{ inputs.directory}} -name "*.map" -delete
        find ${{ inputs.directory}} -name "*.js" | xargs --no-run-if-empty sed -i -e '/\/\/# sourceMappingURL.*/d'
        find ${{ inputs.directory}} -name "*.css" | xargs --no-run-if-empty sed -i -e '/\/\*# sourceMappingURL.*/d'
      shell: bash
